### ISSUE TITLE
Playback queue stops Volumio 2.673

### ISSUE THREAD

**Issue by tomstephens89** [Saiyato/volumio-lastfm-plugin#13]
When this Lastfm scrobbler plugin is installed on the latest Volumio build (2.673), the playback queue will stop after a seemingly random number of tracks has been played.

See report on forum:

https://forum.volumio.org/lastfm-pluign-causes-playback-queue-stop-t13449.html

**Comment by Saiyato** [comment]
I did some refactoring, especially in the case of parsing values, does the same behaviour apply to the latest version? You can pull it from here

**Comment by tomstephens89** [comment]
Can you give me a quick howto on installing your latest version from here into my Volumio pi? 

Im a competent Linux admin. Just need to know install dir etc...

**Comment by Saiyato** [comment]
Easiest would be to use the script listed here: https://github.com/Saiyato/volumio-plugin-helper
This part is relevant: `sh volumio_install_from_zip.sh Saiyato volumio-lastfm-plugin`

Otherwise it's a matter of downloading the zip file from the project, unzipping it and running `npm i` followed by `volumio plugin install` from inside the unzipped folder (remove the zip-file prior to this).

npm i > installs all necessary node modules
volumio plugin install > performs the 'magic' and installs the plugin in the correct location

**Comment by tomstephens89** [comment]
Thanks, I'll give it a go tonight. Is the current version on here newer than whats included in the Volumio GUI then?

**Comment by Saiyato** [comment]
Yes, that's correct, I believe there are still problems with my latest PR, which caused merge conflicts for some reason.

**Comment by tomstephens89** [comment]
volumio@volumio:~$ sh volumio_install_from_zip.sh Saiyato volumio-lastfm-plugin
volumio_install_from_zip.sh: 8: volumio_install_from_zip.sh: Syntax error: newline unexpected

**Comment by tomstephens89** [comment]
Installed and nope, playback still stops.

`
---------------------------- MPD announces state update: player
2019-12-16T19:02:15.627Z - info: ControllerMpd::getState
2019-12-16T19:02:15.629Z - info: ControllerMpd::sendMpdCommand status
2019-12-16T19:02:15.632Z - info: sending command...
2019-12-16T19:02:15.637Z - info: parsing response...
2019-12-16T19:02:15.645Z - info: ControllerMpd::parseState
2019-12-16T19:02:15.647Z - info: ControllerMpd::pushState
2019-12-16T19:02:15.648Z - info: CoreCommandRouter::servicePushState
2019-12-16T19:02:15.656Z - info: CoreStateMachine::syncState
2019-12-16T19:02:15.656Z - info: CoreStateMachine::pushState
2019-12-16T19:02:15.657Z - info: CoreStateMachine::getState
2019-12-16T19:02:15.658Z - info: CorePlayQueue::getTrack 0
2019-12-16T19:02:15.658Z - info: CoreCommandRouter::volumioPushState
2019-12-16T19:02:15.659Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-12-16T19:02:15.708Z - info: CorePlayQueue::getTrack 0
2019-12-16T19:02:15.709Z - info: STATE SERVICE {"status":"stop","position":null,"seek":null,"duration":null,"samplerate":null,"bitdepth":null,"channels":null,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":null,"artist":null,"album":null,"uri":null}
2019-12-16T19:02:15.710Z - info: CURRENT POSITION 0
2019-12-16T19:02:15.711Z - info: CoreStateMachine::syncState   stateService stop
2019-12-16T19:02:15.711Z - info: CoreStateMachine::syncState   currentStatus stop
2019-12-16T19:02:15.712Z - info: CoreStateMachine::pushState
2019-12-16T19:02:15.713Z - info: CoreStateMachine::getState
2019-12-16T19:02:15.713Z - info: CorePlayQueue::getTrack 0
2019-12-16T19:02:15.714Z - info: CoreCommandRouter::volumioPushState
2019-12-16T19:02:15.715Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-12-16T19:02:15.762Z - info: No code
2019-12-16T19:02:15.763Z - info: CoreStateMachine::pushState
2019-12-16T19:02:15.763Z - info: CoreStateMachine::getState
2019-12-16T19:02:15.764Z - info: CorePlayQueue::getTrack 0
2019-12-16T19:02:15.765Z - info: CoreCommandRouter::volumioPushState
2019-12-16T19:02:15.765Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-12-16T19:02:15.841Z - info: ------------------------------ 219ms
2019-12-16T19:02:15.859Z - info: [LastFM] using existing timer
2019-12-16T19:02:15.860Z - info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: stop | service: mpd | duration: 332 | title: The Song Remains The Same | previous title: The Song Remains The Same
2019-12-16T19:02:15.860Z - info: =================> [timer] is active: false | can continue: false | timer started at: undefined
2019-12-16T19:02:15.862Z - info: [LastFM] stopping timer, song has ended.
2019-12-16T19:02:15.866Z - info: [LastFM] using existing timer
2019-12-16T19:02:15.867Z - info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: stop | service: mpd | duration: 332 | title: The Song Remains The Same | previous title: The Song Remains The Same
2019-12-16T19:02:15.867Z - info: =================> [timer] is active: false | can continue: false | timer started at: undefined
2019-12-16T19:02:15.869Z - info: [LastFM] stopping timer, song has ended.
2019-12-16T19:02:15.872Z - info: [LastFM] using existing timer
2019-12-16T19:02:15.873Z - info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: stop | service: mpd | duration: 332 | title: The Song Remains The Same | previous title: The Song Remains The Same
2019-12-16T19:02:15.874Z - info: =================> [timer] is active: false | can continue: false | timer started at: undefined
2019-12-16T19:02:15.875Z - info: [LastFM] stopping timer, song has ended.
`

**Comment by Saiyato** [comment]
Hi there, thanks for trying, can you enable debug logging in the plugin? I'm seeing a fatal error on my installation and a null reference error on the artist property.

**Comment by tomstephens89** [comment]
[Failure log.txt](https://github.com/Saiyato/volumio-lastfm-plugin/files/3969784/Failure.log.txt)

There you go. So this log file covers from the moment when I enabled debug logging in the plugin, through starting my queue, until the playback stops after the first track has finished. You see something goes very very wrong in between, it looks like Volumio runs through its startup procedure. Audio playback does not stop during this.

**Comment by Saiyato** [comment]
I found the culprit! It's a bad line of code, will patch after ~30 minutes of successful playback ;) Testing now

**Comment by tomstephens89** [comment]
> I found the culprit! It's a bad line of code, will patch after ~30 minutes of successful playback ;) Testing now

You are the man if this works and will be on my xmas card list. What was the bad line of code doing?

**Comment by Saiyato** [comment]
I just pushed the fix, found another null reference error case. Lines 948 and 955 of index.js have been patched and I bumped the version number. It should suffice to just overwrite /data/plugins/miscellanea/lastfm/index.js with the new one (keep line endings in mind when using non-unix systems). For completeness you should also bump package.json to version 1.3.4 (if you're experiencing problems, you should reference the correct version) ;)

**Comment by tomstephens89** [comment]
I will install from scratch using the zip helper above.

**Comment by tomstephens89** [comment]
Just installed it using the above script again, version is GUI still showing 1.3.3?

**Comment by tomstephens89** [comment]
Your plugin install script does not pull the new version.

**Comment by Saiyato** [comment]
Just updated the zipfile as well, install script should pull the latest version now. I just pushed the changes only to the files first

**Comment by tomstephens89** [comment]
> Just updated the zipfile as well, install script should pull the latest version now. I just pushed the changes only to the files first

Awesome thanks, I changed the file myself and bumped the version anyway. I am playing back now and will report back in 5 minutes if this has resolved the issue.

**Comment by tomstephens89** [comment]
Well good news so far, over the first track where it failed every time. I will leave a queue running for an hour and report back :-D

**Comment by Saiyato** [comment]
Awesome, thanks! :) I'll do the same with two albums this night as I'm going away and won't look again this evening ;)

**Comment by tomstephens89** [comment]
I played 4 albums in a queue last night and all was fine.

**Comment by kionez** [comment]
Using version 1.3.4 seems fixed, Volumio is playing stable for about 2 hours. 
Thanks!

**Comment by Saiyato** [comment]
Aye, will push this into my PR as well for the Volumio store

**Comment by Saiyato** [comment]
Fixed by last commit

**Comment by oisteink** [comment]
I will add here, even if you have closed it. The issue seems to me to be of memory, once you run out of memory volumio will self-restart and report that the playing device isn't present. 

After a while the last.fm plugin will try to process the same song several times. Not sure if this is connected to tidal, as I'm using a mix of tidal and local tracks. I just see that after a while there becomes duplicate lines in the log from last.fm plugin - from just one extra to several.

Volumio system version: 2.692 19 dec 2019
Last.fm scrobbler version: 1.3.4

Two logs: 
1 is two songs from Tidal
2 is two songs from NAS
[log-2local-songs.txt](https://github.com/Saiyato/volumio-lastfm-plugin/files/3990399/log-2local-songs.txt)
[log-2tidal-songs.txt](https://github.com/Saiyato/volumio-lastfm-plugin/files/3990400/log-2tidal-songs.txt)

**Comment by oisteink** [comment]
One more comment here, and a log. If i disable the plugin it reports as stopped, but will keep on updating last.fm
[log-disableplugin.txt](https://github.com/Saiyato/volumio-lastfm-plugin/files/3990582/log-disableplugin.txt)

EDIT: As a bonus it managed to scrobble a song after I disable the plugin
